name: Package URL Validator

on:
  workflow_run:
    workflows: [ "Python Lint" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Package
      run: make bundle-url-validator-zip
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: url-validator
        path: ./url-validator.zip
        retention-days: 2